// builder
export const GET_DOUGH_ID = "GET_DOUGH_ID";
export const GET_SAUCES_ID = "GET_SAUCES_ID";
export const GET_SIZE_ID = "GET_SIZE_ID";
export const GET_PIZZA_NAME = "GET_PIZZA_NAME";
export const INCREASE_COUNTER = "INCREASE_COUNTER";
export const DECREASE_COUNTER = "DECREASE_COUNTER";
export const RESET_PIZZA = "RESET_PIZZA";
export const SET_PIZZA_PRICE = "SET_PIZZA_PRICE";
export const SET_ORDER_INGREDIENTS = "SET_ORDER_INGREDIENTS";
export const SET_EDIT_PIZZA = "SET_EDIT_PIZZA";
// cart
export const SET_PIZZA_PRICE_CART = "SET_PIZZA_PRICE_CART";
export const ADD_NEW_PIZZA = "ADD_NEW_PIZZA";
export const UPDATE_TOTAL_CART_PRICE = "UPDATE_TOTAL_CART_PRICE";
export const SET_ENTITY = "SET_ENTITY";
export const INCREASE_ADDGOODS_COUNTER = "INCREASE_ADDGOODS_COUNTER";
export const DECREASE_ADDGOODS_COUNTER = "DECREASE_ADDGOODS_COUNTER";
export const RESET_CART = "RESET_CART";
