export const GET_DOUGH_ID = "GET_DOUGH_ID";
export const GET_SAUCES_ID = "GET_SAUCES_ID";
export const GET_SIZE_ID = "GET_SIZE_ID";
export const GET_PIZZA_NAME = "GET_PIZZA_NAME";
export const INCREASE_COUNTER = "INCREASE_COUNTER";
export const DECREASE_COUNTER = "DECREASE_COUNTER";
